var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import styled from "styled-components";
var SkillContainer = styled.section(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  background-color: #ffffff;\n  padding: 4rem;\n  height: 25rem;\n  margin: 5rem 8rem;\n  border-radius: 1rem;\n  box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);\n  display: flex;\n"], ["\n  background-color: #ffffff;\n  padding: 4rem;\n  height: 25rem;\n  margin: 5rem 8rem;\n  border-radius: 1rem;\n  box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);\n  display: flex;\n"])));
var SkillTitleContainer = styled.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  width: 40%;\n  padding-right: 2rem;\n  font-size: 2rem;\n  margin: 2rem 0;\n"], ["\n  width: 40%;\n  padding-right: 2rem;\n  font-size: 2rem;\n  margin: 2rem 0;\n"])));
var SkillDescriptionContainer = styled.div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  width: 60%;\n  font-size: 1.5rem;\n  margin: 2rem 0;\n  display: flex;\n  align-items: center;\n"], ["\n  width: 60%;\n  font-size: 1.5rem;\n  margin: 2rem 0;\n  display: flex;\n  align-items: center;\n"])));
var SkillListContainer = styled.div(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  display: flex;\n  flex-direction: column;\n  justify-content: space-between;\n"], ["\n  display: flex;\n  flex-direction: column;\n  justify-content: space-between;\n"])));
var SkillList = styled.ul(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  list-style: none;\n  margin: 0;\n  padding: 0;\n"], ["\n  list-style: none;\n  margin: 0;\n  padding: 0;\n"])));
var SkillListItem = styled.li(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n  margin-left: 0.2rem;\n  margin-bottom: 0.5rem;\n"], ["\n  margin-left: 0.2rem;\n  margin-bottom: 0.5rem;\n"])));
var SkillListWrapper = styled.div(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n  display: flex;\n  justify-content: space-between;\n"], ["\n  display: flex;\n  justify-content: space-between;\n"])));
var SkillListColumn = styled.div(templateObject_8 || (templateObject_8 = __makeTemplateObject(["\n  display: flex;\n  flex-direction: column;\n  margin-right: 4rem;\n"], ["\n  display: flex;\n  flex-direction: column;\n  margin-right: 4rem;\n"])));
export var SkillContents = function () {
    return (_jsxs(SkillContainer, { children: [_jsx(SkillTitleContainer, { children: _jsx("h2", { children: "Skill" }) }), _jsx(SkillDescriptionContainer, { children: _jsx(SkillListContainer, { children: _jsxs(SkillListWrapper, { children: [_jsx(SkillListColumn, { children: _jsx(SkillList, { children: _jsxs("li", { children: [_jsx("h3", { children: "\u30D5\u30ED\u30F3\u30C8\u30A8\u30F3\u30C9" }), _jsxs(SkillList, { children: [_jsx(SkillListItem, { children: "JavaScript" }), _jsx(SkillListItem, { children: "TypeScript" }), _jsx(SkillListItem, { children: "React.js" })] })] }) }) }), _jsx(SkillListColumn, { children: _jsxs(SkillList, { children: [_jsxs("li", { children: [_jsx("h3", { children: "AI" }), _jsxs(SkillList, { children: [_jsx(SkillListItem, { children: "Python" }), _jsx(SkillListItem, { children: "TensorFlow" }), _jsx(SkillListItem, { children: "PyTorch" })] })] }), _jsxs("li", { children: [_jsx("h3", { children: "\u30C6\u30B9\u30C8" }), _jsx(SkillList, { children: _jsx(SkillListItem, { children: "Cypress" }) })] })] }) }), _jsx(SkillListColumn, { children: _jsx(SkillList, { children: _jsxs("li", { children: [_jsx("h3", { children: "\u30AF\u30E9\u30A6\u30C9" }), _jsx(SkillList, { children: _jsx(SkillListItem, { children: "GoogleCloud" }) })] }) }) })] }) }) })] }));
};
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8;
